apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server
        env:
          - name: PORT
            value: "4000"
        image: jinwoo17962/python-socket-server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: socket-server-service
spec:
  selector:
    app: socket-server
  ports:
  - port: 4000

