apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: logging-elas
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
  - port: 9200
    name: rest
  - port: 9300
    name: inter-node  
