# Default values for metric-monitor.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

grafana:
  name: grafana
  externalIP: ""
  image:
    repository: grafana/grafana
    tag: "8.2.1"
  volume:
    name: grafana-vol
    storage: 2Gi
    hostPath:
      path: /opt/grafana
      type: DirectoryOrCreate
    storageClassName: grafana
    request: 1Gi
  service:
    type: ClusterIP
    port: 3000

prometheus:
  name: prometheus
  externalIP: ""
  image:
    repository: prom/prometheus
    tag: "v2.30.3"
  config:
    name: prometheus-config
  volume:
    name: prometheus-vol
    storage: 2Gi
    hostPath:
      path: /opt/prometheus
      type: DirectoryOrCreate
    storageClassName: prom-volume
    request: 1Gi
  service:
    type: ClusterIP
    port: 9090

nodeExporter:
  name: node-exporter
  image:
    repository: prom/node-exporter
    tag: "v1.2.2"


imagePullSecrets: []


serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
