apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prometheus.volume.name }}
spec:
  capacity:
    storage: {{ .Values.prometheus.volume.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.prometheus.volume.storageClassName }}
  hostPath:
    path: {{ .Values.prometheus.volume.hostPath.path }}
    type: {{ .Values.prometheus.volume.hostPath.type }}