apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.name }}
spec:
  type: {{ .Values.prometheus.service.type}}

  {{- if .Values.prometheus.externalIP }}
  externalIPs:
  - {{ toYaml .Values.prometheus.externalIP }}
  {{- end }}
  selector:
    app: {{ .Values.prometheus.name }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
