apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name}}
  labels:
    app: {{ .Values.kibana.name}}
spec:
  ports:
  - port: 5601
  selector:
    app: {{ .Values.kibana.name}}
  {{- if .Values.kibana.externalIP -}}
  externalIPs:
  -  {{ toYaml .Values.kibana.externalIP }}
  {{- end -}}