apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name}}
  labels:
    app: {{ .Values.elasticsearch.name}}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.elasticsearch.name}}
  ports:
  - port: {{ .Values.elasticsearch.service.rest }}
    name: rest
  - port: {{ .Values.elasticsearch.service.inter }}
    name: inter-node  
