apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.elasticsearch.name }}-cluster
spec:
  serviceName: {{ .Values.elasticsearch.name }}
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name}}
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.elasticsearch.volume.name }}
      initContainers:
      - name: fix-permissions
        image: busybox:1.34.0
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox:1.34.0
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox:1.34.0
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
      containers:
        - name: {{ .Values.elasticsearch.name }}
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
          env:
            - name: cluster.name
              value: k8s-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "{{ .Values.elasticsearch.name}}-cluster-0.{{ .Values.elasticsearch.name}}"
            - name: cluster.initial_master_nodes
              value: "{{ .Values.elasticsearch.name}}-cluster-0"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"