apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.nodeExporter.name }}
  labels:
    name: {{ .Values.nodeExporter.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.nodeExporter.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodeExporter.name }}
      annotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "9100"
    spec:
      volumes:
        - name: root
          hostPath:
            path: "/"
      hostNetwork: true
      hostIPC: true
      hostPID: true
      containers:
        - name: {{ .Values.nodeExporter.name }}
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          volumeMounts:
            - mountPath: "/host"
              name: root
              readOnly: true
          args:
            - "--path.rootfs=/host"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9100