apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.grafana.volume.name }}
spec:
  storageClassName: {{ .Values.grafana.volume.storageClassName }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage:  {{ .Values.grafana.volume.storage }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.grafana.volume.hostPath.path }}
    type : {{ .Values.grafana.volume.hostPath.type }}