apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.grafana.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.name }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      initContainers:
        - name: grafana-data-permission-fix
          image: busybox:1.34.0
          command: ["/bin/chmod", "-R", "777", "/data"]
          volumeMounts:
            - name: {{ .Values.grafana.volume.name }}
              mountPath: /data
      containers:
      - name: {{ .Values.grafana.name }}
        image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
        ports:
        - containerPort: 3000
          name: http-grafana
          protocol: TCP 
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: {{ .Values.grafana.volume.name }}
      volumes:
      - name: {{ .Values.grafana.volume.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.grafana.volume.name }}
