apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.volume.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.grafana.volume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.grafana.volume.request }}